//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан автоматически.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны при
//     повторной генерации кода. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileOperator
{


    public partial class AdminLogin
    {

        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;

        protected global::System.Web.UI.WebControls.Button btnLogin;

        protected global::System.Web.UI.WebControls.Label lblError;
    }
}

