//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан автоматически.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны при
//     повторной генерации кода. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileOperator
{


    public partial class Admin
    {

        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceAdminTariffStatus;

        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceAdminTariffs;

        protected global::System.Web.UI.WebControls.GridView GridViewAdminTariffs;

        protected global::System.Web.UI.WebControls.TextBox txtTariffGb;

        protected global::System.Web.UI.WebControls.TextBox txtTariffMinutes;

        protected global::System.Web.UI.WebControls.TextBox txtTariffSms;

        protected global::System.Web.UI.WebControls.TextBox txtTariffCost;

        protected global::System.Web.UI.WebControls.DropDownList ddlTariffStatus;

        protected global::System.Web.UI.WebControls.Button btnAddTariff;

        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceAdminSubscribers;

        protected global::System.Web.UI.WebControls.GridView GridViewAdminSubscribers;

        protected global::System.Web.UI.WebControls.TextBox txtSubLastName;

        protected global::System.Web.UI.WebControls.TextBox txtSubName;

        protected global::System.Web.UI.WebControls.TextBox txtSubSecondName;

        protected global::System.Web.UI.WebControls.TextBox txtSubEmail;

        protected global::System.Web.UI.WebControls.TextBox txtSubPassword;

        protected global::System.Web.UI.WebControls.TextBox txtSubPassportSeries;

        protected global::System.Web.UI.WebControls.TextBox txtSubPassportNumber;

        protected global::System.Web.UI.WebControls.Button btnAddSubscriber;

        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceAdminContractStatus;

        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceAdminContracts;

        protected global::System.Web.UI.WebControls.GridView GridViewAdminContracts;

        protected global::System.Web.UI.WebControls.DropDownList ddlContractSubscriber;

        protected global::System.Web.UI.WebControls.TextBox txtContractPhone;

        protected global::System.Web.UI.WebControls.DropDownList ddlContractTariff;

        protected global::System.Web.UI.WebControls.DropDownList ddlContractStatusNew;

        protected global::System.Web.UI.WebControls.Button btnAddContract;
    }
}

