//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан автоматически.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны при
//     повторной генерации кода. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileOperator
{


    public partial class Offices
    {

        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceOffices;

        protected global::System.Web.UI.WebControls.GridView GridViewOffices;
    }
}

