//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан автоматически.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны при
//     повторной генерации кода. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileOperator
{


    public partial class SiteMaster
    {

        protected global::System.Web.UI.WebControls.HyperLink lnkHome;

        protected global::System.Web.UI.WebControls.HyperLink lnkTariffs;

        protected global::System.Web.UI.WebControls.HyperLink lnkOffices;

        protected global::System.Web.UI.WebControls.HyperLink lnkCabinet;

        protected global::System.Web.UI.WebControls.HyperLink lnkLogin;

        protected global::System.Web.UI.WebControls.HyperLink lnkRegister;

        protected global::System.Web.UI.WebControls.HyperLink lnkAdmin;

        protected global::System.Web.UI.WebControls.HyperLink lnkAdminLogin;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
    }
}

